### ISSUE TITLE
Are there plans to release privacy-preserving RGB and infrared data?

### ISSUE THREAD

**Issue by Galaxywalk** [ybhbingo/MMFi_dataset#14]
Fine-grained RGB and infrared data can help more research. Has the author considered making the data public after performing necessary privacy protection measures such as mosaic processing? Do the authors have a schedule for this?

**Comment by Marsrocky** [comment]
It's already been open-sourced long ago. Please refer to the README.

![image](https://github.com/user-attachments/assets/77589ab5-e30b-4280-8712-a7f2e5a073b5)

https://drive.google.com/drive/folders/1zDbhfH3BV-xCZVUHmK65EgVV1HMDEYcz?usp=sharing
