### ISSUE TITLE
Any plan to report the raw data of mmwave radar?

### ISSUE THREAD

**Issue by Galaxywalk** [ybhbingo/MMFi_dataset#15]
Refer to the paper, the authors use the algorithm in paper of https://dl.acm.org/doi/pdf/10.1145/3489517.3530522 to process with the mmwave range-doppler data. Although it can generate more data, some temperal information and detailed phase information is lost. Are there any plan to open the raw data (or range-doppler data) of mmwave radars?

**Comment by Marsrocky** [comment]
Thanks for your interest. We do not have a plan to open the raw data.
