### ISSUE TITLE
作者是否可以提供mmfi的WiFi数据的模型测试基准。

### ISSUE THREAD

**Issue by zhangxiaodi** [ybhbingo/MMFi_dataset#16]
在作者新的文章maskFi中，作者实现了95%以上的mmFi数据集的识别率。同时其他方法也可以实现这么高的准确率。作者是否可以提供一些基准模型的识别结果。主要想分析一下作者代码中到底是做了哪几类的识别。也遇到其他人发现实验结果和maskfi文章中不一致的地方。

**Comment by Marsrocky** [comment]
Hi Xiaodi, since MaskFi is still under review yet the msc student has graduated a year ago, regarding that paper, could you send the email to contact the first author? This Github is only for the dataset tool. Thanks a lot!
