### ISSUE TITLE
关键点索引

### ISSUE THREAD

**Issue by BlueSeaHome** [ybhbingo/MMFi_dataset#2]
你好，非常感谢你们能够开源你们的数据集！
image文件夹下面的npy文件是不是对应17个关键点的坐标而不是3通道的图像？
能不能提供一下17个关键点对应的关节名称？

**Comment by ybhbingo** [comment]
你好，

是的，RGB、Infra1和Infra2的.npy文件都是17x2的关键点，采用的是最常用的默认关键点排布，例如HRNet这些网络的输出排布，具体名称为：（按照0-16下标）
0：鼻子
1：眼睛（左）
2：眼睛（右）
3：耳朵（左）
4：耳朵（右）
5：肩膀（左）
6：肩膀（右）
7：肘关节（左）
8：肘关节（右）
9：手腕（左）
10：手腕（右）
11：髋关节（左）
12：髋关节（右）
13：膝盖（左）
14：膝盖（右）
15：脚踝（左）
16：脚踝（右）

谢谢对此数据集的关注，希望能帮到你的研究工作。

**Comment by BlueSeaHome** [comment]
非常感谢
