### ISSUE TITLE
What do infra1 and infra2 mean?

### ISSUE THREAD

**Issue by BlueSeaHome** [ybhbingo/MMFi_dataset#3]
Thank you for your wonderful work!
What do folders infra1 and infra2 mean? Are they representing 2D keypoints?

**Comment by ybhbingo** [comment]
Hi,

Yes, they also represent the 2D keypoints extracted from infra images with the same index meaning as the RGB modality.

Thank you!

**Comment by BlueSeaHome** [comment]
Thank you very much!
