### ISSUE TITLE
keypoints的单位问题

### ISSUE THREAD

**Issue by BlueSeaHome** [ybhbingo/MMFi_dataset#4]
你好，非常感谢你们上次耐心的回答！
我还想请问一下你们的数据集里面的groundtruth.npy的keypoints单位是不是以米（m）为单位？
用你们提供的evaluate.py计算完后的数值是否还需要进行缩放的操作才能得到真实的误差？
非常感谢！

**Comment by ybhbingo** [comment]
你好，

是米（m）为单位的，用evaluate.py后得到的误差就是现实误差，理论上不需要再做缩放转换的。

**Comment by BlueSeaHome** [comment]
好的，非常感谢！
