### ISSUE TITLE
About the complete code file

### ISSUE THREAD

**Issue by yaoerqin** [ybhbingo/MMFi_dataset#7]
Hi there,

      I'm wondering if the complete code file will be uploaded to the github later? I'm a phD student now and want to take this example as my project.

     Really apprecaite your help.

Kind Regards,
Huimin YAO
15811542832
772733879@qq.com

**Comment by Marsrocky** [comment]
Hi Huimin,

We have already released all the codes to access the datasets. What is the complete code file?

Best,
Jianfei

**Comment by yaoerqin** [comment]
Hi Jianfei,


Thanks for your reply.
I mean the "example.py" file is not complete, the model setting, training and testing prpcess is not included yet. I'm not very familiar with the pytorch right now and want to try a complete code file for studying.


Kind Regards,
Huimin YAO




Huimin&nbsp;Yao
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ybhbingo/MMFi_dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月23日(星期四) 上午9:56
***@***.***&gt;;
抄送:&nbsp;"Huimin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ybhbingo/MMFi_dataset] About the complete code file (Issue #7)





 
Hi Huimin,
 
We have already released all the codes to access the datasets. What is the complete code file?
 
Best,
 Jianfei

**Comment by Kuroshika** [comment]
Hi! I am also a reader of MMFi. The author provided a link in the third line below section A.4 Benchmark Implementation Details on page sixteen of the paper published on arXiv on September 25, 2023. Perhaps, this might be helpful for you.

**Comment by yaoerqin** [comment]
Hi, really really appreciate your reply. I have found that and run the code. One more question is in the mmwave directory, the model load the pre-trained parameters, "model.load_state_dict(torch.load('./pre-train_weights/mmwave_p1_random.pt')) "but there is no such file in the directory. So my training error is very large. Did you notice that?




Huimin&nbsp;Yao
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ybhbingo/MMFi_dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月1日(星期五) 下午2:37
***@***.***&gt;;
抄送:&nbsp;"Huimin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ybhbingo/MMFi_dataset] About the complete code file (Issue #7)





 
Hi! I am also a reader of MMFi. The author provided a link in the third line below section A.4 Benchmark Implementation Details on page sixteen of the paper published on arXiv on September 25, 2023. Perhaps, this might be helpful for you.

**Comment by Kuroshika** [comment]
﻿I am glad my advice is helpful. I didn’t run the code, I just want to get the WiFi csi data from mmfi dataset.在 2023年12月11日，21:47，yaohuimin ***@***.***> 写道：﻿
Hi, really really appreciate your reply. I have found that and run the code. One more question is in the mmwave directory, the model load the pre-trained parameters, "model.load_state_dict(torch.load('./pre-train_weights/mmwave_p1_random.pt')) "but there is no such file in the directory. So my training error is very large. Did you notice that?









Huimin&nbsp;Yao

***@***.***







&nbsp;









------------------&nbsp;原始邮件&nbsp;------------------

发件人:                                                                                                                        "ybhbingo/MMFi_dataset"                                                                                    ***@***.***&gt;;

发送时间:&nbsp;2023年12月1日(星期五) 下午2:37

***@***.***&gt;;

抄送:&nbsp;"Huimin ***@***.******@***.***&gt;;

主题:&nbsp;Re: [ybhbingo/MMFi_dataset] About the complete code file (Issue #7)











 

Hi! I am also a reader of MMFi. The author provided a link in the third line below section A.4 Benchmark Implementation Details on page sixteen of the paper published on arXiv on September 25, 2023. Perhaps, this might be helpful for you.

**Comment by sufreebyte** [comment]
> Hi, really really appreciate your reply. I have found that and run the code. One more question is in the mmwave directory, the model load the pre-trained parameters, "model.load_state_dict(torch.load('./pre-train_weights/mmwave_p1_random.pt')) "but there is no such file in the directory. So my training error is very large. Did you notice that? Huimin&nbsp;Yao ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ybhbingo/MMFi_dataset" ***@***.***&gt;; 发送时间:&nbsp;2023年12月1日(星期五) 下午2:37 ***@***.***&gt;; 抄送:&nbsp;"Huimin ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ybhbingo/MMFi_dataset] About the complete code file (Issue #7) Hi! I am also a reader of MMFi. The author provided a link in the third line below section A.4 Benchmark Implementation Details on page sixteen of the paper published on arXiv on September 25, 2023. Perhaps, this might be helpful for you. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hi Huimin,
I think this path is just a dirctory where stores pretrained weights, so you can dir a new directory and change this path by yourself. The pretrained weighted can also be obtained by running the code below in that ipynb.

Best
Yu Liu
